# Generated by Django 4.1 on 2022-08-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='position',
        ),
        migrations.AddField(
            model_name='agent',
            name='department',
            field=models.CharField(default='Agent', max_length=55),
        ),
    ]
